### ISSUE TITLE
The game crashes

### ISSUE THREAD

**Issue by Mika2333** [creepycats/SCProphunt#1]
Could it be due to network fluctuations caused by too many players or playing audio? (I guess)

**Comment by gatodevelowoper** [comment]
Looks like someone ignored the literal fucking comment i left.

REPORT CRASHES WITH YOUR LOGS ON DISCORD.

Crashes happen with the client if you install it properly. If it crashes your whole server you likely did something wrong.

**Comment by gatodevelowoper** [comment]
And for the record the issue is related to Invalid Item Data which I need a LOG to try and fix.
